### PR TITLE
add upgrade plugin & shell

### PR DESCRIPTION
**Pull request by wizardlyk**
Pull Request Description
---

### Describe what this PR does / why we need it
Support ack-d k8s upgrade

### Special notes for reviews

### CODE REVIEW

**Review by VinceCui — COMMENTED** [review]
Kubefile 和 build.sh，是否必须单独一份呢？能否和原先的进行合并？

**Comment by wizardlyk** [comment]
>

**Review by VinceCui — COMMENTED** [review]
Remove code about rollback

**Review by VinceCui — APPROVED** [review]
LGTM

**Pull request merged**
